variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'leanebotegatftec-AzurePortal'
    appType: 'webAppLinux'
    appName: 'webcalculator-app-mab'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'